# Generated by Django 5.0.3 on 2024-04-26 10:12

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Attachmenttype",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the type of attachment",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Jobposition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="The title to be used before the person's name",
                        max_length=50,
                        verbose_name="title",
                    ),
                ),
                (
                    "grade",
                    models.CharField(
                        blank=True,
                        help_text="An indication of the position within a hierarchy, used for ordering in a list",
                        max_length=10,
                        verbose_name="Grade",
                    ),
                ),
            ],
            options={
                "ordering": ["-grade"],
            },
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="The name of the department",
                        max_length=50,
                        verbose_name="name",
                    ),
                ),
                (
                    "container",
                    models.ForeignKey(
                        blank=True,
                        help_text="The departemnt of which this department is part",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spl_members.department",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name_prefered",
                    models.CharField(
                        help_text="The person's first name or prefered name to be used it's place",
                        max_length=20,
                        verbose_name="prefered name",
                    ),
                ),
                (
                    "surname",
                    models.CharField(
                        help_text="The person's surname name, or acceptable alternative",
                        max_length=60,
                        verbose_name="surname",
                    ),
                ),
                (
                    "name_full",
                    models.CharField(
                        help_text="The full name of the member, the format of which should be consistantly applied throughout",
                        max_length=80,
                        verbose_name="full name",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True,
                        help_text="The members's email address",
                        max_length=254,
                        verbose_name="email",
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True,
                        help_text="The member's phone number",
                        max_length=30,
                        verbose_name="phone",
                    ),
                ),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="The date this person started (or will start) - approximate if unknown",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True,
                        default=datetime.date.today,
                        help_text="The date this person was no longer attached this organization.  Blank if still attached",
                        null=True,
                    ),
                ),
                (
                    "department",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person's job position in the organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spl_members.department",
                    ),
                ),
                (
                    "jobposition",
                    models.ForeignKey(
                        blank=True,
                        help_text="The person's job position in the organization",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spl_members.jobposition",
                    ),
                ),
                (
                    "supervisor",
                    models.ForeignKey(
                        blank=True,
                        help_text="The member's supervisor",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="spl_members.member",
                    ),
                ),
            ],
            options={
                "ordering": ("jobposition", "department"),
            },
        ),
    ]
