# Generated by Django 5.0.3 on 2024-04-27 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("spl_members", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="jobposition",
            options={"ordering": ["-grade", "department"]},
        ),
        migrations.AlterModelOptions(
            name="member",
            options={"ordering": ("jobposition",)},
        ),
        migrations.RemoveField(
            model_name="member",
            name="department",
        ),
        migrations.RemoveField(
            model_name="member",
            name="supervisor",
        ),
        migrations.AddField(
            model_name="department",
            name="abbreviation",
            field=models.CharField(
                blank=True,
                help_text="An abbrevation, or code, for the department",
                max_length=10,
                verbose_name="abbreviation",
            ),
        ),
        migrations.AddField(
            model_name="jobposition",
            name="department",
            field=models.ForeignKey(
                blank=True,
                help_text="The position's department",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spl_members.department",
            ),
        ),
        migrations.AddField(
            model_name="jobposition",
            name="supervisor",
            field=models.ForeignKey(
                blank=True,
                help_text="The positions's supervisor",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="spl_members.jobposition",
            ),
        ),
        migrations.AddField(
            model_name="member",
            name="is_individual",
            field=models.BooleanField(
                default=True,
                help_text="Is this member an individual (as opposed to an organization or other entity which might be viewed as an individual for purposes of this data)",
                verbose_name="is an individual",
            ),
        ),
    ]
