# Generated by Django 5.0.3 on 2024-04-29 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_members', '0002_alter_department_options_alter_jobposition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='is_active',
            field=models.BooleanField(default=True, help_text='If the person is currently attached to the organization.', verbose_name='active'),
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, default=None, help_text='The date this person was no longer attached this organization.  Blank if still attached', null=True),
        ),
    ]
