# Generated by Django 5.0.3 on 2024-04-30 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_members', '0003_member_is_active_alter_member_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='member',
            options={'ordering': ('is_active', 'surname', 'start_date')},
        ),
        migrations.AlterField(
            model_name='member',
            name='end_date',
            field=models.DateField(blank=True, help_text='The date this person detached from this organization.  Automatically updated by status of is_active', null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='start_date',
            field=models.DateField(blank=True, help_text='The date this person became part of this organiztion.  Automatically updated by status of is_active', null=True),
        ),
    ]
