# Generated by Django 5.0.6 on 2024-11-11 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spl_members', '0005_jobposition_email_jobposition_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposition',
            name='grade',
            field=models.CharField(blank=True, help_text='For alphabetical ordering.  An indication of the position within a hierarchy', max_length=10, verbose_name='Grade'),
        ),
    ]
